FROM golang:1.22.0 as local

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates git && \
    rm -rf /var/cache/apt/*

RUN go install github.com/cosmtrek/air@v1.51.0
RUN go install github.com/go-delve/delve/cmd/dlv@v1.22.0

WORKDIR /api/

CMD ["air","-c",".air.toml"]
